version: '2'
services:
    m2advertisequiz-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/m2advertiseQuiz/mongodb/:/data/db/
