version: '2'
services:
    m2advertisequiz-mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
        command: mongos --configdb m2advertisequiz-mongodb-config
    m2advertisequiz-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    m2advertisequiz-mongodb-config:
        image: mongo:3.4.8
        container_name: m2advertisequiz-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
